"use client";

import { use, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, Check, ChevronLeft, Eye, Factory, FileText, Loader2, Pause, Play, RefreshCw, Send, ShieldCheck, UserCheck, X, XCircle } from "lucide-react";
import { productionApi, type ProductionRun, type ProductionRunStep, type RunStepStatus } from "@/lib/api/production";
import { formsApi, type Form } from "@/lib/api/forms";
import type { SchemaField } from "@/features/forms/detail/types";
import { FieldRenderer } from "@/features/forms/detail/submission/FieldRenderer";
import { useAuth } from "@/context/AuthContext";

const labels:Record<string,string>={LOCKED:"قفل",READY:"آماده اجرا",IN_PROGRESS:"در حال تکمیل",WAITING_SUPERVISOR:"منتظر ناظر",WAITING_APPROVAL:"منتظر تأیید",NEEDS_REVISION:"نیاز به اصلاح",COMPLETED:"تکمیل",SKIPPED:"رد شده",PAUSED:"متوقف",CANCELLED:"لغو",IN_PROGRESS_RUN:"در حال اجرا"};
const palette:Record<RunStepStatus,{bg:string,border:string,text:string,dot:string}>={LOCKED:{bg:"#f8fafc",border:"#cbd5e1",text:"#64748b",dot:"#94a3b8"},READY:{bg:"#eef2ff",border:"#818cf8",text:"#4338ca",dot:"#6366f1"},IN_PROGRESS:{bg:"#eff6ff",border:"#60a5fa",text:"#1d4ed8",dot:"#3b82f6"},WAITING_SUPERVISOR:{bg:"#f5f3ff",border:"#a78bfa",text:"#6d28d9",dot:"#8b5cf6"},WAITING_APPROVAL:{bg:"#ecfeff",border:"#67e8f9",text:"#0e7490",dot:"#06b6d4"},NEEDS_REVISION:{bg:"#fff7ed",border:"#fb923c",text:"#c2410c",dot:"#f97316"},COMPLETED:{bg:"#ecfdf5",border:"#34d399",text:"#047857",dot:"#10b981"},SKIPPED:{bg:"#fff1f2",border:"#fb7185",text:"#be123c",dot:"#f43f5e"}};

function ReviewDialog({step,type,onClose,onDone}:{step:ProductionRunStep;type:"SUPERVISOR"|"APPROVER";onClose:()=>void;onDone:()=>void}){const [comment,setComment]=useState("");const [busy,setBusy]=useState(false);const act=async(action:"APPROVED"|"REJECTED")=>{setBusy(true);try{if(type==="SUPERVISOR")await productionApi.reviewSupervisor((step as any).runId,step.id,action,comment);else await productionApi.reviewApproval((step as any).runId,step.id,action,comment);onDone();onClose()}finally{setBusy(false)}};return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="fixed inset-0 z-[120] flex items-center justify-center bg-zinc-950/60 p-4 backdrop-blur-sm"><motion.div initial={{scale:.96,y:15}} animate={{scale:1,y:0}} className="w-full max-w-lg rounded-[28px] bg-white p-6 dark:bg-zinc-900" dir="rtl"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-lg font-black">{type==="SUPERVISOR"?<UserCheck className="text-violet-500"/>:<ShieldCheck className="text-cyan-500"/>}{type==="SUPERVISOR"?"بررسی ناظر":"تأیید نهایی"}</div><button onClick={onClose}><X/></button></div><h3 className="mt-5 font-bold">{step.name}</h3><p className="mt-1 text-xs text-zinc-400">فرم ثبت‌شده را بررسی کنید و نتیجه را مشخص کنید.</p><textarea value={comment} onChange={e=>setComment(e.target.value)} rows={4} className="mt-5 w-full rounded-2xl border border-zinc-200 bg-zinc-50 p-3 text-sm outline-none focus:border-indigo-500 dark:border-zinc-700 dark:bg-zinc-800" placeholder="توضیح بررسی (اختیاری)"/><div className="mt-4 grid grid-cols-2 gap-3"><button disabled={busy} onClick={()=>act("REJECTED")} className="flex items-center justify-center gap-2 rounded-2xl bg-rose-500 py-3 font-black text-white"><XCircle size={17}/> رد و ارجاع برای اصلاح</button><button disabled={busy} onClick={()=>act("APPROVED")} className="flex items-center justify-center gap-2 rounded-2xl bg-emerald-600 py-3 font-black text-white">{busy?<Loader2 className="animate-spin" size={17}/>:<Check size={17}/>} تأیید</button></div></motion.div></motion.div>}

function SubmissionPanel({runId,step,onClose,onDone}:{runId:string;step:ProductionRunStep;onClose:()=>void;onDone:()=>void}){const [form,setForm]=useState<Form|null>(null);const [values,setValues]=useState<Record<string,unknown>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState("");useEffect(()=>{formsApi.findById(step.formId).then(r=>setForm(r.data))},[step.formId]);const fields=(form?.schema?.fields||[]) as SchemaField[];const submit=async()=>{for(const f of fields){if(f.required&&(values[f.id]===undefined||values[f.id]===null||values[f.id]==="")){setError(`فیلد «${f.label}» الزامی است`);return}}setBusy(true);setError("");try{await productionApi.submit(runId,step.id,values);onDone();onClose()}catch(e:any){setError(e?.response?.data?.message||"ثبت فرم ناموفق بود")}finally{setBusy(false)}};return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="fixed inset-0 z-[115] bg-zinc-950/55 backdrop-blur-sm"><motion.aside initial={{x:-50,opacity:0}} animate={{x:0,opacity:1}} className="absolute left-0 top-0 h-full w-full max-w-2xl overflow-y-auto bg-zinc-50 shadow-2xl dark:bg-zinc-950" dir="rtl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-zinc-200 bg-white/90 p-5 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/90"><div><div className="flex items-center gap-2 font-black"><FileText className="text-indigo-600"/> {step.name}</div><div className="mt-1 text-xs text-zinc-400">مرحله {step.stepOrder} · {form?.name||"در حال بارگذاری فرم..."}</div></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-zinc-100 dark:hover:bg-zinc-800"><X/></button></div><div className="p-6">{!form?<div className="flex h-52 items-center justify-center"><Loader2 className="animate-spin text-indigo-500"/></div>:<div className="space-y-5">{fields.map(f=><FieldRenderer key={f.id} field={f} value={values[f.id]} onChange={v=>setValues(p=>({...p,[f.id]:v}))}/>)}{error&&<div className="rounded-xl bg-rose-50 p-3 text-sm text-rose-600">{error}</div>}<button onClick={submit} disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-l from-indigo-600 to-violet-600 py-3.5 font-black text-white shadow-lg disabled:opacity-50">{busy?<Loader2 className="animate-spin"/>:<Send size={18}/>} ثبت فرم و ارسال به مرحله بررسی</button></div>}</div></motion.aside></motion.div>}

export default function ProductionRunPage({params}:{params:Promise<{id:string}>}){const {id}=use(params);const {user}=useAuth();const [run,setRun]=useState<ProductionRun|null>(null);const [loading,setLoading]=useState(true);const [submitStep,setSubmitStep]=useState<ProductionRunStep|null>(null);const [review,setReview]=useState<{step:ProductionRunStep;type:"SUPERVISOR"|"APPROVER"}|null>(null);const [selectedStepId,setSelectedStepId]=useState<string|null>(null);const [hoveredStepId,setHoveredStepId]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);try{const r=await productionApi.run(id);setRun(r.data)}finally{setLoading(false)}},[id]);useEffect(()=>{load()},[load]);useEffect(()=>{if(run?.status!=="IN_PROGRESS")return;const timer=setInterval(()=>{load()},10000);return()=>clearInterval(timer)},[run?.status,load]);
  if(loading||!run)return <div className="flex h-[70vh] items-center justify-center"><Loader2 className="animate-spin text-indigo-500" size={36}/></div>;
  const done=run.steps.filter(s=>s.status==="COMPLETED").length,pct=Math.round(done/Math.max(1,run.steps.length)*100);
  const activeStep=run.steps.find(s=>s.id===(hoveredStepId||selectedStepId))||run.steps.find(s=>s.stepOrder===run.currentStepOrder)||run.steps[0];
  const actionFor=(s:ProductionRunStep)=>{const me=user?.id;if(!me)return null;if(s.assigneeUserId===me&&["READY","IN_PROGRESS","NEEDS_REVISION"].includes(s.status))return <button onClick={async()=>{if(s.status==="READY")await productionApi.begin(id,s.id);setSubmitStep(s);load()}} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-3 py-2 text-xs font-black text-white"><FileText size={14}/>{s.status==="NEEDS_REVISION"?"اصلاح و ثبت مجدد":"تکمیل فرم"}</button>;if(s.supervisorUserId===me&&s.status==="WAITING_SUPERVISOR")return <button onClick={()=>setReview({step:{...s,runId:id} as any,type:"SUPERVISOR"})} className="flex items-center gap-2 rounded-xl bg-violet-600 px-3 py-2 text-xs font-black text-white"><UserCheck size={14}/> بررسی ناظر</button>;if(s.approverUserId===me&&s.status==="WAITING_APPROVAL")return <button onClick={()=>setReview({step:{...s,runId:id} as any,type:"APPROVER"})} className="flex items-center gap-2 rounded-xl bg-cyan-600 px-3 py-2 text-xs font-black text-white"><ShieldCheck size={14}/> تأیید نهایی</button>;return null};
  return <div dir="rtl" className="space-y-6 pb-10"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><Link href="/dashboard/production" className="mb-2 inline-flex items-center gap-1 text-xs text-zinc-400 hover:text-indigo-600"><ArrowRight size={14}/> بازگشت به تولید</Link><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-black">{run.title}</h1><span className="rounded-full bg-indigo-500/10 px-3 py-1 text-xs font-bold text-indigo-600">{run.referenceNo}</span></div><p className="mt-2 text-sm text-zinc-400">{run.flow.name} · شروع‌کننده: {run.startedBy.name}</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-zinc-200 p-2.5 dark:border-zinc-800"><RefreshCw size={17}/></button>{run.status==="IN_PROGRESS"&&<button onClick={async()=>{await productionApi.status(id,"pause");load()}} className="flex items-center gap-2 rounded-xl bg-amber-500 px-3 py-2 text-xs font-bold text-white"><Pause size={15}/> توقف</button>}{run.status==="PAUSED"&&<button onClick={async()=>{await productionApi.status(id,"resume");load()}} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><Play size={15}/> ادامه</button>}</div></div>
    <div className="grid gap-4 md:grid-cols-4"><div className="rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="text-xs text-zinc-400">وضعیت</div><div className="mt-2 text-lg font-black">{run.status==="IN_PROGRESS"?"در حال اجرا":run.status==="COMPLETED"?"تکمیل شده":run.status==="PAUSED"?"متوقف موقت":"لغو شده"}</div></div><div className="rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="text-xs text-zinc-400">مرحله جاری</div><div className="mt-2 text-lg font-black">{run.currentStepOrder?`${run.currentStepOrder} از ${run.steps.length}`:"—"}</div></div><div className="rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="text-xs text-zinc-400">مراحل تکمیل</div><div className="mt-2 text-lg font-black">{done} / {run.steps.length}</div></div><div className="rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex justify-between text-xs text-zinc-400"><span>پیشرفت</span><span>{pct}%</span></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800"><motion.div initial={{width:0}} animate={{width:`${pct}%`}} className="h-full rounded-full bg-gradient-to-l from-indigo-500 via-violet-500 to-emerald-400"/></div></div></div>
    <div className="overflow-hidden rounded-[30px] border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900">
      <div className="flex flex-col gap-2 border-b border-zinc-100 p-5 sm:flex-row sm:items-center sm:justify-between dark:border-zinc-800">
        <div>
          <h2 className="flex items-center gap-2 font-black"><Factory className="text-indigo-600"/> مسیر خطی تولید</h2>
          <p className="mt-1 text-xs text-zinc-400">روی هر مرحله نگه دارید تا پیش‌نمایش ببینید؛ با کلیک، جزئیات آن مرحله انتخاب و ثابت می‌شود.</p>
        </div>
        <div className="flex items-center gap-2 text-[11px] text-zinc-400"><span className="h-2.5 w-2.5 rounded-full bg-emerald-500"/> تکمیل شده <span className="mr-2 h-2.5 w-2.5 rounded-full bg-indigo-500"/> مرحله جاری</div>
      </div>

      <div className="overflow-x-auto px-5 pb-8 pt-10 [scrollbar-width:thin]" dir="rtl">
        <div className="relative mx-auto flex min-w-max items-start px-8" style={{width:`${Math.max(720,run.steps.length*210)}px`}}>
          <div className="absolute left-[72px] right-[72px] top-[31px] h-1 rounded-full bg-zinc-200 dark:bg-zinc-800"/>
          <motion.div initial={{width:0}} animate={{width:`${run.steps.length<=1?0:(done/Math.max(1,run.steps.length-1))*100}%`}} transition={{duration:.7,ease:"easeOut"}} className="absolute right-[72px] top-[31px] h-1 max-w-[calc(100%-144px)] rounded-full bg-gradient-to-l from-emerald-500 via-teal-400 to-indigo-500"/>
          {run.steps.map((s,index)=>{const c=palette[s.status];const isCurrent=run.currentStepOrder===s.stepOrder;const isSelected=activeStep?.id===s.id;return <div key={s.id} className="relative z-10 flex flex-1 flex-col items-center" style={{minWidth:190}} onMouseEnter={()=>setHoveredStepId(s.id)} onMouseLeave={()=>setHoveredStepId(null)}>
            <button onClick={()=>setSelectedStepId(s.id)} className="group flex flex-col items-center outline-none" aria-label={`مرحله ${s.stepOrder}: ${s.name}`}>
              <motion.div whileHover={{scale:1.12,y:-2}} whileTap={{scale:.96}} animate={isCurrent?{boxShadow:[`0 0 0 0 ${c.dot}00`,`0 0 0 14px ${c.dot}22`,`0 0 0 0 ${c.dot}00`]}:{}} transition={isCurrent?{repeat:Infinity,duration:2}:undefined} style={{background:c.bg,borderColor:isSelected?c.dot:c.border,color:c.text}} className={`relative flex h-16 w-16 items-center justify-center rounded-full border-[3px] text-base font-black shadow-md transition-all ${isSelected?"ring-4 ring-zinc-900/5 dark:ring-white/10":""}`}>
                {s.status==="COMPLETED"?<Check size={24}/>:s.stepOrder}
                {isCurrent&&<span style={{background:c.dot}} className="absolute -bottom-1 -right-1 h-4 w-4 rounded-full border-2 border-white dark:border-zinc-900"/>}
              </motion.div>
              <div className={`mt-3 max-w-[165px] truncate text-sm font-black transition-colors ${isSelected?"text-zinc-950 dark:text-white":"text-zinc-600 dark:text-zinc-300"}`}>{s.name}</div>
              <div style={{color:c.text,background:c.bg}} className="mt-1 rounded-full px-2.5 py-1 text-[10px] font-bold">{labels[s.status]}</div>
            </button>
            {index<run.steps.length-1&&<ChevronLeft className="pointer-events-none absolute -left-3 top-[22px] text-zinc-300 dark:text-zinc-700" size={18}/>} 
          </div>})}
        </div>
      </div>
    </div>

    <AnimatePresence mode="wait">
      {activeStep&&<motion.div key={activeStep.id} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.2}} className="rounded-[28px] border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
        {(()=>{const s=activeStep;const c=palette[s.status];return <>
          <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start">
            <div className="flex items-start gap-4">
              <div style={{background:c.bg,color:c.text,borderColor:c.border}} className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border-2 text-lg font-black">{s.status==="COMPLETED"?<Check size={24}/>:s.stepOrder}</div>
              <div>
                <div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-black">{s.name}</h3><span style={{background:c.bg,color:c.text}} className="rounded-full px-3 py-1 text-[10px] font-bold">{labels[s.status]}</span>{s.attempt>0&&<span className="rounded-full bg-zinc-100 px-2.5 py-1 text-[10px] text-zinc-500 dark:bg-zinc-800">تلاش {s.attempt}</span>}</div>
                <p className="mt-2 text-xs text-zinc-400">مرحله {s.stepOrder} از {run.steps.length}</p>
                {s.description&&<p className="mt-3 max-w-2xl text-sm leading-7 text-zinc-500 dark:text-zinc-400">{s.description}</p>}
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-2">{s.submission&&<button onClick={()=>alert(JSON.stringify(s.submission?.data,null,2))} className="flex items-center gap-2 rounded-xl border border-zinc-200 px-3 py-2 text-xs font-bold hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800"><Eye size={14}/> مشاهده پاسخ</button>}{actionFor(s)}</div>
          </div>

          <div className="mt-5 grid gap-3 md:grid-cols-3">
            <div className="rounded-2xl bg-zinc-50 p-4 dark:bg-zinc-800/60"><div className="text-[10px] font-bold text-zinc-400">مسئول اجرا</div><div className="mt-1.5 text-sm font-black">{s.assignee.name}</div></div>
            <div className="rounded-2xl bg-zinc-50 p-4 dark:bg-zinc-800/60"><div className="text-[10px] font-bold text-zinc-400">ناظر</div><div className="mt-1.5 text-sm font-black">{s.supervisor?.name||"بدون ناظر"}</div></div>
            <div className="rounded-2xl bg-zinc-50 p-4 dark:bg-zinc-800/60"><div className="text-[10px] font-bold text-zinc-400">تأییدکننده</div><div className="mt-1.5 text-sm font-black">{s.approver?.name||"بدون تأییدکننده"}</div></div>
          </div>

          {s.reviews.length>0&&<div className="mt-5 border-t border-zinc-100 pt-4 dark:border-zinc-800"><div className="mb-3 text-xs font-black text-zinc-500">تاریخچه بررسی</div><div className="flex flex-wrap gap-2">{s.reviews.map(r=><div key={r.id} className={`rounded-xl px-3 py-2 text-xs ${r.action==="APPROVED"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30":"bg-rose-50 text-rose-700 dark:bg-rose-950/30"}`}><b>{r.type==="SUPERVISOR"?"ناظر":"تأییدکننده"}:</b> {r.reviewer.name} · {r.action==="APPROVED"?"تأیید":"رد"}{r.comment&&` — ${r.comment}`}</div>)}</div></div>}
        </>})()}
      </motion.div>}
    </AnimatePresence>
    <AnimatePresence>{submitStep&&<SubmissionPanel runId={id} step={submitStep} onClose={()=>setSubmitStep(null)} onDone={load}/>}</AnimatePresence><AnimatePresence>{review&&<ReviewDialog step={review.step} type={review.type} onClose={()=>setReview(null)} onDone={load}/>}</AnimatePresence>
  </div>
}
