CREATE TYPE "RecruitmentFormType" AS ENUM ('PRE_INTERVIEW','INITIAL_INTERVIEW','TECHNICAL_INTERVIEW','SUPERADMIN_REVIEW','PROFILE_COMPLETION');
CREATE TYPE "RecruitmentApplicationStatus" AS ENUM ('DRAFT','IN_PROGRESS','REJECTED','WITHDRAWN','HIRED','CANCELLED');
CREATE TYPE "RecruitmentStage" AS ENUM ('PRE_INTERVIEW_FORM','INITIAL_REVIEW','INITIAL_INTERVIEW','TECHNICAL_INTERVIEW_ASSIGNMENT','TECHNICAL_INTERVIEW','SUPERADMIN_APPROVAL','ACCOUNT_PROVISIONING','PROFILE_COMPLETION','COMPLETED');
CREATE TYPE "RecruitmentActorType" AS ENUM ('APPLICANT','USER','SYSTEM');
CREATE TYPE "RecruitmentAction" AS ENUM ('SUBMIT_PRE_INTERVIEW','APPROVE_INITIAL_REVIEW','REJECT_INITIAL_REVIEW','SUBMIT_INITIAL_INTERVIEW','APPROVE_INITIAL_INTERVIEW','REJECT_INITIAL_INTERVIEW','ASSIGN_TECHNICAL_INTERVIEWER','SUBMIT_TECHNICAL_INTERVIEW','APPROVE_TECHNICAL_INTERVIEW','REJECT_TECHNICAL_INTERVIEW','FINAL_APPROVE','FINAL_REJECT','CREATE_USER_ACCOUNT','COMPLETE_PROFILE','WITHDRAW','REASSIGN');
CREATE TYPE "InterviewRecommendation" AS ENUM ('STRONG_HIRE','HIRE','NO_HIRE','STRONG_NO_HIRE');

CREATE TABLE "RecruitmentFormTemplate" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"type" "RecruitmentFormType" NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "RecruitmentFormTemplate_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecruitmentFormVersion" ("id" TEXT NOT NULL,"templateId" TEXT NOT NULL,"version" INTEGER NOT NULL,"schema" JSONB NOT NULL,"isPublished" BOOLEAN NOT NULL DEFAULT false,"publishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "RecruitmentFormVersion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JobOpening" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"slug" TEXT NOT NULL,"description" TEXT,"departmentId" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"preInterviewFormId" TEXT NOT NULL,"initialInterviewFormId" TEXT,"technicalInterviewFormId" TEXT,"initialReviewerRoleId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "JobOpening_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecruitmentApplicant" ("id" TEXT NOT NULL,"fullName" TEXT NOT NULL,"phoneNumber" TEXT NOT NULL,"normalizedPhone" TEXT NOT NULL,"email" TEXT,"nationalCode" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "RecruitmentApplicant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecruitmentApplication" ("id" TEXT NOT NULL,"trackingCode" TEXT NOT NULL,"publicTokenHash" TEXT NOT NULL,"applicantId" TEXT NOT NULL,"jobOpeningId" TEXT NOT NULL,"status" "RecruitmentApplicationStatus" NOT NULL DEFAULT 'IN_PROGRESS',"currentStage" "RecruitmentStage" NOT NULL DEFAULT 'INITIAL_REVIEW',"finalUserId" TEXT,"rejectionReasonInternal" TEXT,"rejectionMessagePublic" TEXT,"version" INTEGER NOT NULL DEFAULT 0,"submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"rejectedAt" TIMESTAMP(3),"hiredAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "RecruitmentApplication_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecruitmentFormSubmission" ("id" TEXT NOT NULL,"applicationId" TEXT NOT NULL,"formVersionId" TEXT NOT NULL,"stage" "RecruitmentStage" NOT NULL,"answers" JSONB NOT NULL,"submittedByType" "RecruitmentActorType" NOT NULL,"submittedByUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "RecruitmentFormSubmission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecruitmentAssignment" ("id" TEXT NOT NULL,"applicationId" TEXT NOT NULL,"stage" "RecruitmentStage" NOT NULL,"assigneeUserId" TEXT NOT NULL,"assignedByUserId" TEXT NOT NULL,"assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),"revokedAt" TIMESTAMP(3),CONSTRAINT "RecruitmentAssignment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecruitmentTransition" ("id" TEXT NOT NULL,"applicationId" TEXT NOT NULL,"fromStage" "RecruitmentStage","toStage" "RecruitmentStage" NOT NULL,"action" "RecruitmentAction" NOT NULL,"actorType" "RecruitmentActorType" NOT NULL,"actorUserId" TEXT,"reasonCode" TEXT,"comment" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "RecruitmentTransition_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TechnicalInterviewEvaluation" ("id" TEXT NOT NULL,"applicationId" TEXT NOT NULL,"interviewerId" TEXT NOT NULL,"overallScore" INTEGER NOT NULL,"recommendation" "InterviewRecommendation" NOT NULL,"internalSummary" TEXT NOT NULL,"completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TechnicalInterviewEvaluation_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "RecruitmentFormVersion_templateId_version_key" ON "RecruitmentFormVersion"("templateId","version");
CREATE INDEX "RecruitmentFormVersion_templateId_isPublished_idx" ON "RecruitmentFormVersion"("templateId","isPublished");
CREATE UNIQUE INDEX "JobOpening_slug_key" ON "JobOpening"("slug");
CREATE INDEX "JobOpening_isActive_idx" ON "JobOpening"("isActive");
CREATE INDEX "RecruitmentApplicant_normalizedPhone_idx" ON "RecruitmentApplicant"("normalizedPhone");
CREATE INDEX "RecruitmentApplicant_nationalCode_idx" ON "RecruitmentApplicant"("nationalCode");
CREATE UNIQUE INDEX "RecruitmentApplication_trackingCode_key" ON "RecruitmentApplication"("trackingCode");
CREATE UNIQUE INDEX "RecruitmentApplication_publicTokenHash_key" ON "RecruitmentApplication"("publicTokenHash");
CREATE UNIQUE INDEX "RecruitmentApplication_finalUserId_key" ON "RecruitmentApplication"("finalUserId");
CREATE INDEX "RecruitmentApplication_status_currentStage_idx" ON "RecruitmentApplication"("status","currentStage");
CREATE INDEX "RecruitmentApplication_jobOpeningId_createdAt_idx" ON "RecruitmentApplication"("jobOpeningId","createdAt");
CREATE UNIQUE INDEX "RecruitmentFormSubmission_applicationId_stage_key" ON "RecruitmentFormSubmission"("applicationId","stage");
CREATE INDEX "RecruitmentFormSubmission_formVersionId_idx" ON "RecruitmentFormSubmission"("formVersionId");
CREATE INDEX "RecruitmentAssignment_assigneeUserId_stage_completedAt_idx" ON "RecruitmentAssignment"("assigneeUserId","stage","completedAt");
CREATE INDEX "RecruitmentAssignment_applicationId_stage_idx" ON "RecruitmentAssignment"("applicationId","stage");
CREATE INDEX "RecruitmentTransition_applicationId_createdAt_idx" ON "RecruitmentTransition"("applicationId","createdAt");
CREATE UNIQUE INDEX "TechnicalInterviewEvaluation_applicationId_key" ON "TechnicalInterviewEvaluation"("applicationId");
CREATE INDEX "TechnicalInterviewEvaluation_interviewerId_idx" ON "TechnicalInterviewEvaluation"("interviewerId");

ALTER TABLE "RecruitmentFormVersion" ADD CONSTRAINT "RecruitmentFormVersion_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "RecruitmentFormTemplate"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JobOpening" ADD CONSTRAINT "JobOpening_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "JobOpening" ADD CONSTRAINT "JobOpening_preInterviewFormId_fkey" FOREIGN KEY ("preInterviewFormId") REFERENCES "RecruitmentFormTemplate"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "JobOpening" ADD CONSTRAINT "JobOpening_initialInterviewFormId_fkey" FOREIGN KEY ("initialInterviewFormId") REFERENCES "RecruitmentFormTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "JobOpening" ADD CONSTRAINT "JobOpening_technicalInterviewFormId_fkey" FOREIGN KEY ("technicalInterviewFormId") REFERENCES "RecruitmentFormTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecruitmentApplication" ADD CONSTRAINT "RecruitmentApplication_applicantId_fkey" FOREIGN KEY ("applicantId") REFERENCES "RecruitmentApplicant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecruitmentApplication" ADD CONSTRAINT "RecruitmentApplication_jobOpeningId_fkey" FOREIGN KEY ("jobOpeningId") REFERENCES "JobOpening"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecruitmentApplication" ADD CONSTRAINT "RecruitmentApplication_finalUserId_fkey" FOREIGN KEY ("finalUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecruitmentFormSubmission" ADD CONSTRAINT "RecruitmentFormSubmission_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitmentApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecruitmentFormSubmission" ADD CONSTRAINT "RecruitmentFormSubmission_formVersionId_fkey" FOREIGN KEY ("formVersionId") REFERENCES "RecruitmentFormVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecruitmentFormSubmission" ADD CONSTRAINT "RecruitmentFormSubmission_submittedByUserId_fkey" FOREIGN KEY ("submittedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecruitmentAssignment" ADD CONSTRAINT "RecruitmentAssignment_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitmentApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecruitmentAssignment" ADD CONSTRAINT "RecruitmentAssignment_assigneeUserId_fkey" FOREIGN KEY ("assigneeUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecruitmentAssignment" ADD CONSTRAINT "RecruitmentAssignment_assignedByUserId_fkey" FOREIGN KEY ("assignedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecruitmentTransition" ADD CONSTRAINT "RecruitmentTransition_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitmentApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecruitmentTransition" ADD CONSTRAINT "RecruitmentTransition_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TechnicalInterviewEvaluation" ADD CONSTRAINT "TechnicalInterviewEvaluation_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "RecruitmentApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;
