"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { FileText, Loader2, Search, ArrowLeft, ListFilter } from "lucide-react";
import { formsApi, type Form } from "@/lib/api/forms";
export default function FillFormsPage(){const [forms,setForms]=useState<Form[]>([]);const [loading,setLoading]=useState(true);const [q,setQ]=useState("");
useEffect(()=>{formsApi.findAll().then(r=>setForms(r.data.filter(f=>f.isActive))).catch(()=>setForms([])).finally(()=>setLoading(false))},[]);
const visible=useMemo(()=>{const s=q.trim().toLowerCase();return !s?forms:forms.filter(f=>[f.name,f.customId,f.description].some(v=>v?.toLowerCase().includes(s)))},[forms,q]);
return <div dir="rtl" className="space-y-6"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">جستجو و تکمیل فرم</h1><p className="mt-1 text-sm text-gray-500">فرم موردنظر را پیدا کنید و مستقیماً آن را تکمیل کنید.</p></div>
<div className="relative max-w-3xl"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400" size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="نام، کد یا توضیحات فرم را جستجو کنید..." className="w-full rounded-2xl border border-gray-200 bg-white py-3.5 pr-12 pl-4 text-sm outline-none focus:border-blue-400 dark:border-gray-700 dark:bg-gray-900"/></div>
{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-500"/></div>:visible.length===0?<div className="rounded-2xl border border-dashed p-12 text-center text-sm text-gray-500"><ListFilter className="mx-auto mb-3 text-gray-300"/>فرمی با این مشخصات پیدا نشد.</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(f=><Link key={f.id} href={`/dashboard/forms/fill/${f.id}`} className="group rounded-2xl border border-gray-100 bg-white p-5 hover:border-blue-200 hover:shadow-sm dark:border-gray-800 dark:bg-gray-900"><div className="flex items-start gap-3"><div className="rounded-xl bg-blue-50 p-2.5 text-blue-600 dark:bg-blue-500/10"><FileText size={19}/></div><div className="min-w-0 flex-1"><h2 className="font-semibold text-gray-900 dark:text-white">{f.name}</h2>{f.customId&&<p className="mt-1 text-xs font-mono text-blue-500">#{f.customId}</p>}<p className="mt-2 line-clamp-2 text-xs leading-5 text-gray-500">{f.description||"بدون توضیحات"}</p></div></div><div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-3 text-xs dark:border-gray-800"><span className="text-gray-400">{f.schema?.fields?.length??0} فیلد</span><span className="flex items-center gap-1 font-semibold text-blue-600">تکمیل فرم <ArrowLeft size={13}/></span></div></Link>)}</div>}</div>}
