"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, FileText, Loader2, ShieldCheck, TimerReset, XCircle } from "lucide-react";
import { formsApi, type FormsAnalyticsOverview } from "@/lib/api/forms";
import ChartCard from "@/components/charts/ChartCard";
import AnalyticsLineChart from "@/components/charts/AnalyticsLineChart";

type Range = "7d" | "30d" | "90d";
function Kpi({title,value,sub,icon:Icon}:{title:string;value:string;sub:string;icon:typeof FileText}){return <div className="rounded-2xl border border-gray-100 bg-white p-4 dark:border-gray-800 dark:bg-gray-900"><div className="flex justify-between gap-3"><div><p className="text-xs text-gray-500">{title}</p><p className="mt-2 text-2xl font-bold text-gray-900 dark:text-white">{value}</p><p className="mt-1 text-xs text-gray-400">{sub}</p></div><Icon size={18} className="text-blue-500"/></div></div>}
export default function FormsAnalyticsOverviewPage(){
 const [range,setRange]=useState<Range>("30d"); const [data,setData]=useState<FormsAnalyticsOverview|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);formsApi.getAnalyticsOverview(range).then((r: { data: FormsAnalyticsOverview })=>{if(active)setData(r.data)}).catch(()=>{if(active)setData(null)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[range]);
 const labels=useMemo(()=>data?.trend.map((x: FormsAnalyticsOverview["trend"][number])=>new Date(x.date).toLocaleDateString("fa-IR",{month:"short",day:"numeric"}))??[],[data]);
 return <div dir="rtl" className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">تحلیل فرم‌ها</h1><p className="mt-1 text-sm text-gray-500">نمای مدیریتی همه فرم‌های تحت مدیریت شما.</p></div><div className="flex items-center gap-2"><div className="flex rounded-xl bg-gray-100 p-1 dark:bg-gray-800">{(["7d","30d","90d"] as Range[]).map(r=><button key={r} onClick={()=>setRange(r)} className={`rounded-lg px-3 py-2 text-xs ${range===r?"bg-white text-blue-600 shadow-sm dark:bg-gray-900":"text-gray-500"}`}>{r==="7d"?"۷ روز":r==="30d"?"۳۰ روز":"۹۰ روز"}</button>)}</div><Link href="/dashboard/forms/manage" className="rounded-xl border border-gray-200 px-3 py-2 text-sm dark:border-gray-700">مدیریت فرم‌ها</Link></div></div>
 {loading&&!data?<div className="flex justify-center py-24"><Loader2 className="animate-spin text-blue-500"/></div>:!data?<div className="py-20 text-center text-gray-500">داده‌ای در دسترس نیست.</div>:<><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Kpi title="کل پاسخ‌ها" value={data.kpis.submissions.toLocaleString("fa-IR")} sub={data.kpis.submissionsChangePct==null?"بدون مبنای مقایسه":`${data.kpis.submissionsChangePct}% نسبت به قبل`} icon={FileText}/><Kpi title="نرخ تأیید" value={`${data.kpis.approvalRate}%`} sub={`${data.kpis.approved} تأیید`} icon={CheckCircle2}/><Kpi title="نرخ رد" value={`${data.kpis.rejectionRate}%`} sub={`${data.kpis.rejected} رد`} icon={XCircle}/><Kpi title="میانگین زمان تصمیم" value={data.kpis.averageProcessingHours==null?"—":`${data.kpis.averageProcessingHours} ساعت`} sub={`${data.kpis.pending} در انتظار`} icon={TimerReset}/></div>
 <ChartCard title="روند کل پاسخ‌ها" subtitle="تمام فرم‌های تحت مدیریت"><AnalyticsLineChart labels={labels} series={[{name:"پاسخ",data:data.trend.map((x: FormsAnalyticsOverview["trend"][number])=>x.count)}]}/></ChartCard>
 <div className="grid grid-cols-1 gap-4 md:grid-cols-3"><Kpi title="SLA Compliance" value={data.sla.complianceRate==null?"—":`${data.sla.complianceRate}%`} sub={`${data.sla.assessed} مورد ارزیابی`} icon={ShieldCheck}/><Kpi title="داخل SLA" value={data.sla.within.toLocaleString("fa-IR")} sub="در بازه انتخابی" icon={CheckCircle2}/><Kpi title="نقض SLA" value={data.sla.breached.toLocaleString("fa-IR")} sub="نیازمند بررسی" icon={AlertTriangle}/></div>

 <section className="overflow-hidden rounded-2xl border border-gray-100 bg-white dark:border-gray-800 dark:bg-gray-900"><div className="border-b border-gray-100 p-4 dark:border-gray-800"><h2 className="font-semibold text-gray-900 dark:text-white">فرم‌های پرتکرار</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="bg-gray-50 text-gray-500 dark:bg-gray-800/40"><th className="p-3 text-right">فرم</th><th className="p-3">پاسخ</th><th className="p-3">تأیید</th><th className="p-3">رد</th><th className="p-3">در انتظار</th><th className="p-3">SLA هدف</th><th className="p-3">رعایت SLA</th><th className="p-3">تحلیل</th></tr></thead><tbody>{data.forms.map((form: FormsAnalyticsOverview["forms"][number])=><tr key={form.id} className="border-t border-gray-100 dark:border-gray-800"><td className="p-3 font-medium text-gray-900 dark:text-white">{form.name ?? "فرم"}</td><td className="p-3 text-center">{form.submissions}</td><td className="p-3 text-center">{form.approved}</td><td className="p-3 text-center">{form.rejected}</td><td className="p-3 text-center">{form.pending}</td><td className="p-3 text-center">{form.slaTargetHours==null?"—":`${form.slaTargetHours}h`}</td><td className="p-3 text-center">{form.slaComplianceRate==null?"—":`${form.slaComplianceRate}%`}</td><td className="p-3 text-center">{form.id&&<Link href={`/dashboard/forms/manage/${form.id}/analytics`} className="inline-flex items-center gap-1 text-blue-600"><BarChart3 size={14}/> مشاهده</Link>}</td></tr>)}</tbody></table></div></section></>}
 </div>
}
