"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import {
  Activity, Boxes, CheckCircle2, CircleDashed, Factory, GitBranch, ListChecks,
  Loader2, Plus, Play, Settings2, Sparkles, Trash2, UserCheck, Users, X, Eye,
  Clock3, ShieldCheck, ChevronDown, ChevronUp, GripVertical
} from "lucide-react";
import { usePermission } from "@/hooks/usePermission";
import { productionApi, type FlowPayload, type ProductionFlow, type ProductionRun, type ProductionRunStep, type ProductionFormRef, type ProductionUser } from "@/lib/api/production";

const statusFa: Record<string,string> = { IN_PROGRESS:"در حال اجرا", PAUSED:"متوقف موقت", COMPLETED:"تکمیل شده", CANCELLED:"لغو شده", READY:"آماده", LOCKED:"قفل", WAITING_SUPERVISOR:"در انتظار ناظر", WAITING_APPROVAL:"در انتظار تأیید", NEEDS_REVISION:"نیاز به اصلاح" };
const statusClass: Record<string,string> = { IN_PROGRESS:"bg-blue-500/10 text-blue-600", PAUSED:"bg-amber-500/10 text-amber-600", COMPLETED:"bg-emerald-500/10 text-emerald-600", CANCELLED:"bg-rose-500/10 text-rose-600", READY:"bg-indigo-500/10 text-indigo-600", LOCKED:"bg-slate-500/10 text-slate-500", WAITING_SUPERVISOR:"bg-violet-500/10 text-violet-600", WAITING_APPROVAL:"bg-cyan-500/10 text-cyan-600", NEEDS_REVISION:"bg-orange-500/10 text-orange-600" };

function Metric({icon,title,value,sub}:{icon:React.ReactNode,title:string,value:string|number,sub:string}){
  return <motion.div whileHover={{y:-3}} className="rounded-3xl border border-white/60 bg-white/80 p-5 shadow-sm backdrop-blur-xl dark:border-white/10 dark:bg-zinc-900/80">
    <div className="flex items-center justify-between"><div className="rounded-2xl bg-indigo-500/10 p-3 text-indigo-600">{icon}</div><Sparkles className="text-indigo-300" size={17}/></div>
    <div className="mt-4 text-3xl font-black text-zinc-900 dark:text-white">{value}</div><div className="mt-1 text-sm font-bold text-zinc-700 dark:text-zinc-200">{title}</div><div className="mt-1 text-xs text-zinc-400">{sub}</div>
  </motion.div>
}

function FlowCard({flow,onStart,onDelete,canStart,canDelete}:{flow:ProductionFlow,onStart:(f:ProductionFlow)=>void,onDelete:(f:ProductionFlow)=>void,canStart:boolean,canDelete:boolean}){
  return <motion.div layout whileHover={{y:-4}} className="group overflow-hidden rounded-[28px] border border-zinc-200/70 bg-white shadow-sm transition-shadow hover:shadow-xl dark:border-zinc-800 dark:bg-zinc-900">
    <div className="relative h-24 overflow-hidden bg-gradient-to-l from-indigo-600 via-violet-600 to-fuchsia-600 p-5 text-white">
      <div className="absolute -left-6 -top-12 h-28 w-28 rounded-full bg-white/15 blur-xl"/><div className="absolute right-20 -bottom-10 h-24 w-24 rounded-full bg-cyan-300/20 blur-xl"/>
      <div className="relative flex items-start justify-between"><div><div className="flex items-center gap-2"><Factory size={20}/><h3 className="font-black">{flow.name}</h3></div><p className="mt-1 text-xs text-white/70">{flow.code || "بدون کد"}</p></div><span className="rounded-full bg-white/15 px-3 py-1 text-[11px] backdrop-blur">{flow.isActive?"فعال":"غیرفعال"}</span></div>
    </div>
    <div className="p-5"><p className="min-h-10 text-sm leading-6 text-zinc-500 dark:text-zinc-400">{flow.description || "بدون توضیحات"}</p>
      <div className="mt-4 flex items-center gap-2 overflow-hidden pb-2">
        {flow.steps.slice(0,6).map((s,i)=><div key={s.id||i} className="flex min-w-0 items-center gap-2"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-indigo-100 bg-indigo-50 text-xs font-black text-indigo-600 dark:border-indigo-900 dark:bg-indigo-950/50">{i+1}</div>{i<Math.min(flow.steps.length,6)-1&&<div className="h-[2px] w-5 bg-gradient-to-l from-indigo-300 to-violet-300"/>}</div>)}
        {flow.steps.length>6&&<span className="text-xs text-zinc-400">+{flow.steps.length-6}</span>}
      </div>
      <div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-zinc-50 p-2 dark:bg-zinc-800"><div className="font-black">{flow.steps.length}</div><div className="text-[10px] text-zinc-400">مرحله</div></div><div className="rounded-2xl bg-zinc-50 p-2 dark:bg-zinc-800"><div className="font-black">{flow._count?.runs||0}</div><div className="text-[10px] text-zinc-400">اجرا</div></div><div className="rounded-2xl bg-zinc-50 p-2 dark:bg-zinc-800"><div className="font-black">{new Set(flow.steps.map(s=>s.assigneeUserId)).size}</div><div className="text-[10px] text-zinc-400">مسئول</div></div></div>
      <div className="mt-5 flex gap-2"><button disabled={!canStart||!flow.isActive} onClick={()=>onStart(flow)} className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-zinc-950 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40 dark:bg-white dark:text-zinc-900"><Play size={15}/> شروع تولید</button>{canDelete&&<button onClick={()=>onDelete(flow)} className="rounded-2xl border border-rose-100 px-3 text-rose-500 hover:bg-rose-50 dark:border-rose-900/50 dark:hover:bg-rose-950/30"><Trash2 size={16}/></button>}</div>
    </div>
  </motion.div>
}

type DraftStep={key:string;name:string;description:string;formId:string;assigneeUserId:string;supervisorUserId:string;approverUserId:string;estimatedMinutes:string};
const blankStep=():DraftStep=>({key:crypto.randomUUID(),name:"",description:"",formId:"",assigneeUserId:"",supervisorUserId:"",approverUserId:"",estimatedMinutes:""});

function FlowBuilder({open,onClose,onSaved,forms,users}:{open:boolean;onClose:()=>void;onSaved:()=>void;forms:ProductionFormRef[];users:ProductionUser[]}){
  const [name,setName]=useState(""); const [code,setCode]=useState(""); const [description,setDescription]=useState(""); const [steps,setSteps]=useState<DraftStep[]>([blankStep()]); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [expanded,setExpanded]=useState<string|null>(null);
  useEffect(()=>{if(open){setName("");setCode("");setDescription("");setSteps([blankStep()]);setError("");}},[open]);
  const patch=(key:string,p:Partial<DraftStep>)=>setSteps(s=>s.map(x=>x.key===key?{...x,...p}:x));
  const move=(i:number,d:number)=>setSteps(s=>{const n=[...s],j=i+d;if(j<0||j>=n.length)return s;[n[i],n[j]]=[n[j],n[i]];return n});
  const save=async()=>{if(!name.trim())return setError("نام Flow الزامی است");if(steps.some(s=>!s.name||!s.formId||!s.assigneeUserId))return setError("نام مرحله، فرم و مسئول در همه مراحل الزامی است");setBusy(true);setError("");try{const payload:FlowPayload={name:name.trim(),code:code.trim()||undefined,description:description.trim()||undefined,steps:steps.map((s,i)=>({stepOrder:i+1,name:s.name,description:s.description||undefined,formId:s.formId,assigneeUserId:s.assigneeUserId,supervisorUserId:s.supervisorUserId||undefined,approverUserId:s.approverUserId||undefined,estimatedMinutes:s.estimatedMinutes?Number(s.estimatedMinutes):undefined}))};await productionApi.createFlow(payload);onSaved();onClose();}catch(e:any){setError(e?.response?.data?.message||"خطا در ذخیره Flow");}finally{setBusy(false)}};
  return <AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[100] flex items-center justify-center bg-zinc-950/60 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><motion.div initial={{scale:.96,y:20,opacity:0}} animate={{scale:1,y:0,opacity:1}} exit={{scale:.96,y:20,opacity:0}} className="max-h-[92vh] w-full max-w-6xl overflow-hidden rounded-[32px] bg-zinc-50 shadow-2xl dark:bg-zinc-950" dir="rtl">
    <div className="flex items-center justify-between border-b border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><div><div className="flex items-center gap-2 text-xl font-black"><GitBranch className="text-indigo-600"/> ساخت Flow تولید</div><p className="mt-1 text-xs text-zinc-400">فرم‌های موجود را به یک روند عملیاتی مرحله‌ای تبدیل کنید.</p></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-zinc-100 dark:hover:bg-zinc-800"><X/></button></div>
    <div className="max-h-[calc(92vh-150px)] overflow-y-auto p-6"><div className="grid gap-4 md:grid-cols-3"><label className="md:col-span-1"><span className="mb-1.5 block text-xs font-bold text-zinc-500">نام Flow *</span><input value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3 outline-none focus:border-indigo-400 dark:border-zinc-800 dark:bg-zinc-900" placeholder="مثلاً تولید دستگاه X"/></label><label><span className="mb-1.5 block text-xs font-bold text-zinc-500">کد</span><input value={code} onChange={e=>setCode(e.target.value)} className="w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3 outline-none focus:border-indigo-400 dark:border-zinc-800 dark:bg-zinc-900" placeholder="PRD-X"/></label><label><span className="mb-1.5 block text-xs font-bold text-zinc-500">توضیح</span><input value={description} onChange={e=>setDescription(e.target.value)} className="w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3 outline-none focus:border-indigo-400 dark:border-zinc-800 dark:bg-zinc-900" placeholder="شرح کوتاه خط تولید"/></label></div>
      <div className="mt-8 flex items-center justify-between"><div><h3 className="font-black">مراحل Flow</h3><p className="text-xs text-zinc-400">ترتیب مرحله‌ها تعیین‌کننده ترتیب فعال‌شدن فرم‌هاست.</p></div><button onClick={()=>setSteps(s=>[...s,blankStep()])} className="flex items-center gap-2 rounded-2xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white"><Plus size={15}/> افزودن مرحله</button></div>
      <div className="relative mt-5 space-y-3 before:absolute before:right-[27px] before:top-7 before:bottom-7 before:w-[2px] before:bg-gradient-to-b before:from-indigo-500 before:via-violet-400 before:to-fuchsia-400">
        {steps.map((s,i)=><motion.div layout key={s.key} className="relative flex gap-4"><div className="z-10 flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-600 to-violet-600 text-lg font-black text-white shadow-lg shadow-indigo-500/20">{i+1}</div><div className="flex-1 rounded-[24px] border border-zinc-200 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-center gap-3"><GripVertical className="text-zinc-300" size={18}/><input value={s.name} onChange={e=>patch(s.key,{name:e.target.value})} className="min-w-0 flex-1 bg-transparent font-black outline-none" placeholder={`نام مرحله ${i+1}`}/><button onClick={()=>move(i,-1)} disabled={i===0} className="rounded-lg p-1 disabled:opacity-20"><ChevronUp size={16}/></button><button onClick={()=>move(i,1)} disabled={i===steps.length-1} className="rounded-lg p-1 disabled:opacity-20"><ChevronDown size={16}/></button><button onClick={()=>setExpanded(expanded===s.key?null:s.key)} className="rounded-lg p-1 text-zinc-400"><Settings2 size={16}/></button>{steps.length>1&&<button onClick={()=>setSteps(x=>x.filter(a=>a.key!==s.key))} className="rounded-lg p-1 text-rose-500"><Trash2 size={16}/></button>}</div>
          <div className="mt-4 grid gap-3 md:grid-cols-4"><select value={s.formId} onChange={e=>patch(s.key,{formId:e.target.value})} className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">انتخاب فرم *</option>{forms.map(f=><option key={f.id} value={f.id}>{f.customId?`${f.customId} - `:""}{f.name}</option>)}</select><select value={s.assigneeUserId} onChange={e=>patch(s.key,{assigneeUserId:e.target.value})} className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">مسئول اجرا *</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select value={s.supervisorUserId} onChange={e=>patch(s.key,{supervisorUserId:e.target.value})} className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">ناظر (اختیاری)</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select value={s.approverUserId} onChange={e=>patch(s.key,{approverUserId:e.target.value})} className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">تأییدکننده (اختیاری)</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div>
          <AnimatePresence>{expanded===s.key&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><div className="mt-3 grid gap-3 border-t border-zinc-100 pt-3 md:grid-cols-3 dark:border-zinc-800"><input value={s.description} onChange={e=>patch(s.key,{description:e.target.value})} className="md:col-span-2 rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-800" placeholder="توضیح مرحله"/><input type="number" value={s.estimatedMinutes} onChange={e=>patch(s.key,{estimatedMinutes:e.target.value})} className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-800" placeholder="زمان تخمینی (دقیقه)"/></div></motion.div>}</AnimatePresence>
        </div></motion.div>)}
      </div>{error&&<div className="mt-5 rounded-2xl bg-rose-50 p-3 text-sm text-rose-600 dark:bg-rose-950/30">{error}</div>}
    </div><div className="flex justify-end gap-2 border-t border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><button onClick={onClose} className="rounded-2xl px-5 py-2.5 text-sm font-bold text-zinc-500">انصراف</button><button onClick={save} disabled={busy} className="flex items-center gap-2 rounded-2xl bg-gradient-to-l from-indigo-600 to-violet-600 px-6 py-2.5 text-sm font-black text-white shadow-lg shadow-indigo-500/20 disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={16}/>:<CheckCircle2 size={16}/>} ذخیره Flow</button></div>
  </motion.div></motion.div>}</AnimatePresence>
}

function StartRunModal({flow,onClose,onStarted}:{flow:ProductionFlow|null,onClose:()=>void,onStarted:()=>void}){const [title,setTitle]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");useEffect(()=>{if(flow)setTitle(`${flow.name} - ${new Date().toLocaleDateString("fa-IR")}`)},[flow]);const start=async()=>{if(!flow||!title.trim())return;setBusy(true);try{await productionApi.startRun(flow.id,{title});onStarted();onClose()}catch(e:any){setError(e?.response?.data?.message||"شروع اجرا ناموفق بود")}finally{setBusy(false)}};return <AnimatePresence>{flow&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[110] flex items-center justify-center bg-zinc-950/60 p-4 backdrop-blur-sm"><motion.div initial={{scale:.95}} animate={{scale:1}} className="w-full max-w-lg rounded-[28px] bg-white p-6 shadow-2xl dark:bg-zinc-900" dir="rtl"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-lg font-black"><Play className="text-emerald-500"/> شروع اجرای جدید</div><button onClick={onClose}><X/></button></div><p className="mt-2 text-sm text-zinc-400">Flow: {flow.name} · {flow.steps.length} مرحله</p><label className="mt-5 block text-xs font-bold text-zinc-500">عنوان اجرا</label><input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full rounded-2xl border border-zinc-200 px-4 py-3 outline-none focus:border-indigo-500 dark:border-zinc-700 dark:bg-zinc-800"/>{error&&<p className="mt-3 text-xs text-rose-500">{error}</p>}<button onClick={start} disabled={busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-600 py-3 font-black text-white disabled:opacity-50">{busy?<Loader2 className="animate-spin"/>:<Play size={18}/>} ایجاد و فعال‌سازی مرحله اول</button></motion.div></motion.div>}</AnimatePresence>}

export default function ProductionPage(){
  const canCreateFlow=usePermission("create","production-flows"); const canDeleteFlow=usePermission("delete","production-flows"); const canCreateRun=usePermission("create","production-runs");
  const [flows,setFlows]=useState<ProductionFlow[]>([]);const [runs,setRuns]=useState<ProductionRun[]>([]);const [tasks,setTasks]=useState<ProductionRunStep[]>([]);const [forms,setForms]=useState<ProductionFormRef[]>([]);const [users,setUsers]=useState<ProductionUser[]>([]);const [loading,setLoading]=useState(true);const [builder,setBuilder]=useState(false);const [startFlow,setStartFlow]=useState<ProductionFlow|null>(null);const [tab,setTab]=useState<"flows"|"runs"|"tasks">("flows");
  const load=async()=>{setLoading(true);try{const req:any[]=[productionApi.flows(),productionApi.runs(),productionApi.myTasks()];if(canCreateFlow)req.push(productionApi.catalog());const res=await Promise.all(req);setFlows(res[0].data);setRuns(res[1].data);setTasks(res[2].data);if(canCreateFlow){setForms(res[3].data.forms);setUsers(res[3].data.users)}}finally{setLoading(false)}}; useEffect(()=>{load()},[canCreateFlow]);
  const active=runs.filter(r=>r.status==="IN_PROGRESS").length;const completed=runs.filter(r=>r.status==="COMPLETED").length;const progressAvg=useMemo(()=>runs.length?Math.round(runs.reduce((a,r)=>a+(r.steps.filter(s=>s.status==="COMPLETED").length/Math.max(r.steps.length,1))*100,0)/runs.length):0,[runs]);
  const del=async(f:ProductionFlow)=>{if(!confirm(`Flow «${f.name}» حذف/غیرفعال شود؟`))return;await productionApi.deleteFlow(f.id);load()};
  return <div dir="rtl" className="min-h-screen space-y-6 pb-10"><div className="relative overflow-hidden rounded-[32px] bg-zinc-950 p-7 text-white shadow-2xl"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(99,102,241,.35),transparent_30%),radial-gradient(circle_at_80%_30%,rgba(217,70,239,.22),transparent_28%)]"/><motion.div animate={{x:[0,20,0],y:[0,-10,0]}} transition={{duration:8,repeat:Infinity}} className="absolute -left-10 top-4 h-40 w-40 rounded-full bg-indigo-500/20 blur-3xl"/><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold text-indigo-300"><Factory size={16}/> Production Flow Engine</div><h1 className="text-3xl font-black md:text-4xl">تولید و گردش عملیات</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-zinc-400">فرم‌های سازمان را به Pipelineهای واقعی تبدیل کنید؛ مسئول، ناظر و تأییدکننده تعیین کنید و اجرای هر محصول را مرحله‌به‌مرحله دنبال کنید.</p></div>{canCreateFlow&&<button onClick={()=>setBuilder(true)} className="flex shrink-0 items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-black text-zinc-950 shadow-xl"><Plus size={18}/> ساخت Flow جدید</button>}</div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={<GitBranch/>} title="Flowهای تولید" value={flows.length} sub="الگوهای تعریف‌شده"/><Metric icon={<Activity/>} title="در حال اجرا" value={active} sub="Run فعال در حال پردازش"/><Metric icon={<CheckCircle2/>} title="تکمیل‌شده" value={completed} sub="اجرای به پایان رسیده"/><Metric icon={<CircleDashed/>} title="میانگین پیشرفت" value={`${progressAvg}%`} sub="تمام اجراهای ثبت‌شده"/></div>
    <div className="flex gap-2 overflow-x-auto rounded-2xl border border-zinc-200 bg-white p-1.5 dark:border-zinc-800 dark:bg-zinc-900">{([["flows","Flowها",GitBranch],["runs","اجراها",Boxes],["tasks","کارهای من",ListChecks]] as const).map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`flex min-w-max items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition ${tab===k?"bg-zinc-950 text-white dark:bg-white dark:text-zinc-950":"text-zinc-500 hover:bg-zinc-50 dark:hover:bg-zinc-800"}`}><I size={16}/>{l}{k==="tasks"&&tasks.length>0&&<span className="rounded-full bg-rose-500 px-1.5 text-[10px] text-white">{tasks.length}</span>}</button>)}</div>
    {loading?<div className="flex h-64 items-center justify-center"><Loader2 className="animate-spin text-indigo-500" size={36}/></div>:<AnimatePresence mode="wait">{tab==="flows"&&<motion.div key="flows" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{flows.map(f=><FlowCard key={f.id} flow={f} canStart={canCreateRun} canDelete={canDeleteFlow} onStart={setStartFlow} onDelete={del}/>)}{!flows.length&&<div className="col-span-full rounded-3xl border border-dashed border-zinc-300 p-16 text-center text-zinc-400">هنوز Flow تولیدی ساخته نشده است.</div>}</motion.div>}
      {tab==="runs"&&<motion.div key="runs" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="space-y-3">{runs.map(r=>{const done=r.steps.filter(s=>s.status==="COMPLETED").length;const pct=Math.round(done/Math.max(r.steps.length,1)*100);return <Link key={r.id} href={`/dashboard/production/runs/${r.id}`} className="group block rounded-[24px] border border-zinc-200 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-lg dark:border-zinc-800 dark:bg-zinc-900"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-600 text-white"><Factory/></div><div><div className="flex items-center gap-2"><h3 className="font-black">{r.title}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusClass[r.status]}`}>{statusFa[r.status]}</span></div><p className="mt-1 text-xs text-zinc-400">{r.referenceNo} · {r.flow.name}</p></div></div><div className="flex min-w-[280px] items-center gap-3"><div className="flex-1"><div className="mb-1 flex justify-between text-[10px] text-zinc-400"><span>پیشرفت</span><span>{pct}%</span></div><div className="h-2 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800"><motion.div initial={{width:0}} animate={{width:`${pct}%`}} className="h-full rounded-full bg-gradient-to-l from-indigo-500 to-emerald-400"/></div></div><Eye className="text-zinc-300 transition group-hover:text-indigo-500"/></div></div></Link>})}{!runs.length&&<div className="rounded-3xl border border-dashed border-zinc-300 p-16 text-center text-zinc-400">هنوز اجرای تولیدی ثبت نشده است.</div>}</motion.div>}
      {tab==="tasks"&&<motion.div key="tasks" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tasks.map((t:any)=><Link key={t.id} href={`/dashboard/production/runs/${t.run.id}`} className="rounded-[24px] border border-zinc-200 bg-white p-5 transition hover:shadow-lg dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-start justify-between"><div className="rounded-2xl bg-indigo-500/10 p-3 text-indigo-600">{t.status==="WAITING_APPROVAL"?<ShieldCheck/>:t.status==="WAITING_SUPERVISOR"?<UserCheck/>:<ListChecks/>}</div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusClass[t.status]}`}>{statusFa[t.status]||t.status}</span></div><h3 className="mt-4 font-black">{t.name}</h3><p className="mt-1 text-xs text-zinc-400">{t.run?.referenceNo} · {t.run?.flow?.name}</p><div className="mt-4 flex items-center gap-2 text-xs text-zinc-500"><Clock3 size={14}/> مرحله {t.stepOrder}</div></Link>)}{!tasks.length&&<div className="col-span-full rounded-3xl border border-dashed border-zinc-300 p-16 text-center text-zinc-400">در حال حاضر کاری برای شما وجود ندارد.</div>}</motion.div>}</AnimatePresence>}
    <FlowBuilder open={builder} onClose={()=>setBuilder(false)} onSaved={load} forms={forms} users={users}/><StartRunModal flow={startFlow} onClose={()=>setStartFlow(null)} onStarted={load}/>
  </div>
}
