"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Clock3, FileCheck2, FileText, Loader2, Search, SlidersHorizontal, Sparkles } from "lucide-react";
import { formsApi, type Form } from "@/lib/api/forms";

type Sort = "recent" | "name" | "fields";
const recentKey = "forms.recent";

export default function FillFormsPage(){
 const [forms,setForms]=useState<Form[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[sort,setSort]=useState<Sort>("recent"),[recent,setRecent]=useState<string[]>([]);
 useEffect(()=>{try{setRecent(JSON.parse(localStorage.getItem(recentKey)||"[]"))}catch{};formsApi.findAll().then(r=>setForms(r.data.filter(f=>f.isActive))).catch(()=>setForms([])).finally(()=>setLoading(false))},[]);
 const visible=useMemo(()=>{const s=q.trim().toLowerCase();let a=forms.filter(f=>!s||[f.name,f.customId,f.description].some(v=>v?.toLowerCase().includes(s)));return [...a].sort((x,y)=>sort==="name"?x.name.localeCompare(y.name,"fa"):sort==="fields"?(y.schema?.fields?.length??0)-(x.schema?.fields?.length??0):new Date(y.updatedAt).getTime()-new Date(x.updatedAt).getTime())},[forms,q,sort]);
 const recentForms=recent.map(id=>forms.find(f=>f.id===id)).filter(Boolean).slice(0,4) as Form[];
 const remember=(id:string)=>{const n=[id,...recent.filter(x=>x!==id)].slice(0,8);localStorage.setItem(recentKey,JSON.stringify(n))};
 return <div dir="rtl" className="space-y-7">
  <section className="overflow-hidden rounded-3xl border border-blue-100 bg-gradient-to-l from-blue-50 via-white to-indigo-50 p-6 dark:border-blue-950 dark:from-blue-950/40 dark:via-gray-950 dark:to-indigo-950/30"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-blue-600"><Sparkles size={16}/> مرکز فرم‌های سازمانی</div><h1 className="text-2xl font-black text-gray-900 dark:text-white">فرم موردنظرتان را پیدا و تکمیل کنید</h1><p className="mt-2 text-sm text-gray-500">جستجو بر اساس نام، کد یا توضیحات فرم و دسترسی سریع به فرم‌های اخیر.</p></div><div className="rounded-2xl bg-white/80 px-4 py-3 text-sm shadow-sm dark:bg-gray-900/80"><b>{forms.length}</b> فرم فعال</div></div>
   <div className="relative mt-6 max-w-4xl"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400" size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="مثلاً درخواست خرید، مرخصی یا کد فرم..." className="w-full rounded-2xl border border-gray-200 bg-white py-4 pr-12 pl-4 text-sm shadow-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-500/10 dark:border-gray-700 dark:bg-gray-900"/></div>
  </section>
  {recentForms.length>0&&!q&&<section><div className="mb-3 flex items-center gap-2"><Clock3 size={17} className="text-violet-500"/><h2 className="font-bold">فرم‌های اخیر شما</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{recentForms.map(f=><Link onClick={()=>remember(f.id)} key={f.id} href={`/dashboard/forms/fill/${f.id}`} className="rounded-2xl border bg-white p-4 hover:border-violet-300 dark:border-gray-800 dark:bg-gray-900"><div className="font-semibold">{f.name}</div><div className="mt-2 text-xs text-gray-400">{f.schema?.fields?.length??0} فیلد · {f.customId?`#${f.customId}`:"بدون کد"}</div></Link>)}</div></section>}
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">همه فرم‌های قابل تکمیل</h2><p className="mt-1 text-xs text-gray-400">{visible.length} نتیجه</p></div><label className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs dark:border-gray-800 dark:bg-gray-900"><SlidersHorizontal size={15}/><select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="bg-transparent outline-none"><option value="recent">آخرین بروزرسانی</option><option value="name">نام فرم</option><option value="fields">تعداد فیلد</option></select></label></div>
  {loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-500"/></div>:visible.length===0?<div className="rounded-3xl border border-dashed p-14 text-center text-sm text-gray-500"><FileCheck2 className="mx-auto mb-3 text-gray-300" size={36}/>فرمی با این مشخصات پیدا نشد.</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(f=><Link onClick={()=>remember(f.id)} key={f.id} href={`/dashboard/forms/fill/${f.id}`} className="group rounded-3xl border border-gray-100 bg-white p-5 transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-lg hover:shadow-blue-500/5 dark:border-gray-800 dark:bg-gray-900"><div className="flex items-start gap-3"><div className="rounded-2xl bg-blue-50 p-3 text-blue-600 dark:bg-blue-500/10"><FileText size={20}/></div><div className="min-w-0 flex-1"><h3 className="font-bold text-gray-900 dark:text-white">{f.name}</h3>{f.customId&&<p className="mt-1 text-xs font-mono text-blue-500">#{f.customId}</p>}<p className="mt-3 line-clamp-2 min-h-10 text-xs leading-5 text-gray-500">{f.description||"بدون توضیحات"}</p></div></div><div className="mt-5 flex items-center justify-between border-t pt-4 text-xs dark:border-gray-800"><span className="text-gray-400">{f.schema?.fields?.length??0} فیلد</span><span className="flex items-center gap-1 font-bold text-blue-600">شروع تکمیل <ArrowLeft size={14}/></span></div></Link>)}</div>}
 </div>
}
