"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, Clock3, FileText, History, Loader2, Search, XCircle } from "lucide-react";
import { submissionsApi } from "@/lib/api/forms";
type Status="ALL"|"PENDING"|"APPROVED"|"REJECTED";
type Mine={id:string;formId:string;formVersion:number;createdAt:string;form?:{id:string;name:string;customId?:string};approvalInstances?:{status:"PENDING"|"APPROVED"|"REJECTED";currentStepOrder:number|null;updatedAt:string;actions?:{comments?:string|null;action:string}[]}[]};
const meta={PENDING:{label:"در انتظار تایید",cls:"bg-amber-50 text-amber-700 dark:bg-amber-500/10",icon:Clock3},APPROVED:{label:"تایید شده",cls:"bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10",icon:CheckCircle2},REJECTED:{label:"رد شده",cls:"bg-rose-50 text-rose-700 dark:bg-rose-500/10",icon:XCircle}};
export default function MySubmissionsPage(){const [rows,setRows]=useState<Mine[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[status,setStatus]=useState<Status>("ALL");useEffect(()=>{submissionsApi.findMine().then(r=>setRows(r.data as Mine[])).catch(()=>setRows([])).finally(()=>setLoading(false))},[]);const getStatus=(x:Mine)=>x.approvalInstances?.[0]?.status??"APPROVED";const filtered=useMemo(()=>rows.filter(x=>(!q||(x.form?.name??"").toLowerCase().includes(q.toLowerCase())||(x.form?.customId??"").toLowerCase().includes(q.toLowerCase()))&&(status==="ALL"||getStatus(x)===status)),[rows,q,status]);const counts={ALL:rows.length,PENDING:rows.filter(x=>getStatus(x)==="PENDING").length,APPROVED:rows.filter(x=>getStatus(x)==="APPROVED").length,REJECTED:rows.filter(x=>getStatus(x)==="REJECTED").length};
return <div dir="rtl" className="space-y-6"><div><h1 className="text-2xl font-black text-gray-900 dark:text-white">پاسخ‌های من</h1><p className="mt-1 text-sm text-gray-500">وضعیت فرم‌های ارسالی و روند بررسی آن‌ها را دنبال کنید.</p></div>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{(["ALL","PENDING","APPROVED","REJECTED"] as Status[]).map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-2xl border p-4 text-right transition ${status===s?"border-blue-400 ring-4 ring-blue-500/10":"border-gray-100 dark:border-gray-800"} bg-white dark:bg-gray-900`}><div className="text-2xl font-black">{counts[s]}</div><div className="mt-1 text-xs text-gray-500">{s==="ALL"?"کل پاسخ‌ها":meta[s].label}</div></button>)}</div>
<div className="relative max-w-xl"><Search size={17} className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو با نام یا کد فرم..." className="w-full rounded-2xl border border-gray-200 bg-white py-3.5 pr-11 pl-4 text-sm outline-none focus:border-blue-400 dark:border-gray-700 dark:bg-gray-900"/></div>
{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-500"/></div>:filtered.length===0?<div className="rounded-3xl border border-dashed p-12 text-center text-sm text-gray-500"><History className="mx-auto mb-3 text-gray-300"/>پاسخی در این وضعیت پیدا نشد.</div>:<div className="grid gap-3">{filtered.map(r=>{const s=getStatus(r);const m=meta[s];const Icon=m.icon;const instance=r.approvalInstances?.[0];return <div key={r.id} className="rounded-2xl border border-gray-100 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex gap-3"><div className="rounded-xl bg-gray-50 p-3 dark:bg-gray-800"><FileText size={19}/></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{r.form?.name??"فرم"}</h3><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-bold ${m.cls}`}><Icon size={12}/>{m.label}</span></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-400"><span>{new Date(r.createdAt).toLocaleDateString("fa-IR")}</span><span>نسخه {r.formVersion}</span>{r.form?.customId&&<span>#{r.form.customId}</span>}{s==="PENDING"&&instance?.currentStepOrder&&<span>مرحله تایید {instance.currentStepOrder}</span>}</div>{s==="REJECTED"&&instance?.actions?.[0]?.comments&&<p className="mt-2 text-xs text-rose-600">دلیل: {instance.actions[0].comments}</p>}</div></div><div className="flex items-center gap-2"><Link href={`/dashboard/forms/fill/${r.formId}`} className="rounded-xl border px-3 py-2 text-xs font-semibold hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-800">تکمیل مجدد</Link><span className="rounded-xl bg-gray-50 px-3 py-2 font-mono text-[11px] text-gray-400 dark:bg-gray-800">{r.id.slice(0,8)}</span></div></div></div>})}</div>}</div>}
